version: "3.0"
services:
  mysqldb:
    image: kiceurope/mysqldb_dev:QA
    container_name: mysqldb
    build: configuration/docker/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=changeMe
      - MYSQL_USER=edci
      - MYSQL_PASSWORD=changeMe
    volumes:
      - "C://Dev/EDCI/dockers/docker_mysql/datadir:/var/lib/mysql"
    ports:
      - 3307:3306
      - 33060:33060
    healthcheck:
      test: [ "CMD-SHELL", 'mysqladmin ping' ]
      timeout: 5s
      retries: 6
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=changeMe
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://mysqldb:3306/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=changeMe
      - KC_FEATURES=token-exchange,admin-fine-grained-authz
    ports:
      - "9009:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
  issuer:
    image: kiceurope/issuer_dev:QA
    container_name: issuer
    user: edci
    build: edci-issuer/
    environment:
      - JPDA_ENABLED=true
      - JPDA_TRANSPORT=dt_socket
      - JPDA_ADDRESS=*:8000
      - WAIT_FOR_HOST=mysqldb
      - WAIT_FOR_PORT=3306
      - WAIT_FOR_TIMEOUT=60
    volumes:
      - "C://Dev/EDCI/dockers/docker_issuer/edci:/usr/local/tomcat/conf/edci"
      - "C://Dev/EDCI/dockers/docker_issuer/credentials:/usr/local/tomcat/temp/credentials"
      - "C://Dev/EDCI/dockers/docker_issuer/logs:/usr/local/tomcat/logs"
    ports:
      - "8383:8080"
      - "9383:8000"
    depends_on:
      mysqldb:
        condition: service_healthy
  wallet:
    image: kiceurope/wallet_dev:QA
    container_name: wallet
    user: edci
    build: edci-wallet/
    environment:
      - JPDA_ENABLED=true
      - JPDA_TRANSPORT=dt_socket
      - JPDA_ADDRESS=*:8000
      - WAIT_FOR_HOST=mysqldb
      - WAIT_FOR_PORT=3306
      - WAIT_FOR_TIMEOUT=60
    volumes:
      - "C://Dev/EDCI/dockers/docker_wallet/edci:/usr/local/tomcat/conf/edci"
      - "C://Dev/EDCI/dockers/docker_wallet/logs:/usr/local/tomcat/logs"
      - "C://Dev/EDCI/dockers/docker_wallet/wallets:/usr/local/tomcat/temp/wallets"
    ports:
      - "8181:8080"
      - "9181:8000"
    depends_on:
      mysqldb:
        condition: service_healthy
  viewer:
    image: kiceurope/viewer_dev:QA
    container_name: viewer
    user: edci
    build: edci-viewer/
    environment:
      - JPDA_ENABLED=true
      - JPDA_TRANSPORT=dt_socket
      - JPDA_ADDRESS=*:8000
      - WAIT_FOR_HOST=mysqldb
      - WAIT_FOR_PORT=3306
      - WAIT_FOR_TIMEOUT=60
    volumes:
      - "C://Dev/EDCI/dockers/docker_viewer/edci:/usr/local/tomcat/conf/edci"
      - "C://Dev/EDCI/dockers/docker_viewer/logs:/usr/local/tomcat/logs"
    ports:
      - "8282:8080"
      - "9282:8000"
    depends_on:
      mysqldb:
        condition: service_healthy
networks:
  default:
    driver: bridge