/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeDTDAO } from './codeDTDAO';
import { IdentifierDTDAO } from './identifierDTDAO';
import { NoteDTDAO } from './noteDTDAO';
import { OrganizationSpecDAO } from './organizationSpecDAO';
import { TextDTDAO } from './textDTDAO';
import { TextScoreDTDAO } from './textScoreDTDAO';
import { WebDocumentDCDAO } from './webDocumentDCDAO';


export interface AccreditationDCDAO { 
    pk?: number;
    identifier?: Array<IdentifierDTDAO>;
    accreditationType?: CodeDTDAO;
    title?: TextDTDAO;
    description?: NoteDTDAO;
    decision?: TextScoreDTDAO;
    report?: WebDocumentDCDAO;
    organization?: OrganizationSpecDAO;
    limitField?: Array<CodeDTDAO>;
    limitEqfLevel?: Array<CodeDTDAO>;
    limitJurisdiction?: Array<CodeDTDAO>;
    accreditingAgent?: OrganizationSpecDAO;
    issueDate?: Date;
    reviewDate?: Date;
    expiryDate?: Date;
    additionalNote?: Array<NoteDTDAO>;
    homePage?: Array<WebDocumentDCDAO>;
    supplementaryDocument?: Array<WebDocumentDCDAO>;
}
