/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdditionalInfo } from './additionalInfo';
import { CodeDTView } from './codeDTView';
import { SubresourcesOids } from './subresourcesOids';
import { TextDTView } from './textDTView';
import { WebDocumentDCView } from './webDocumentDCView';


export interface AccreditationSpecView { 
    oid?: number;
    additionalInfo?: AdditionalInfo;
    displayName?: string;
    label?: string;
    defaultLanguage: string;
    title?: TextDTView;
    dcType?: CodeDTView;
    report?: WebDocumentDCView;
    status?: CodeDTView;
    limitField?: Array<CodeDTView>;
    limitEQFLevel?: Array<CodeDTView>;
    limitJurisdiction?: Array<CodeDTView>;
    dateIssued?: string;
    languages?: Array<string>;
    expiryDate?: string;
    supplementaryDocument?: Array<WebDocumentDCView>;
    relAccreditingAgent?: SubresourcesOids;
    relOrganisation?: SubresourcesOids;
}
