/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeDTView } from './codeDTView';
import { NoteDTView } from './noteDTView';
import { StandardDTView } from './standardDTView';
import { TextDTView } from './textDTView';


export interface AssociationObjectDTView { 
    associationType?: CodeDTView;
    description?: TextDTView;
    issueDate?: string;
    isAssociationFor?: string;
    targetFramework?: StandardDTView;
    targetFrameworkVersion?: string;
    targetResource?: string;
    targetNotation?: string;
    targetName?: TextDTView;
    targetDescription?: NoteDTView;
    targetUrl?: Array<string>;
}
