/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssessmentSpecDAO } from './assessmentSpecDAO';
import { IdentifierDTDAO } from './identifierDTDAO';
import { LocationDCDAO } from './locationDCDAO';
import { OrganizationSpecDAO } from './organizationSpecDAO';
import { TextDTDAO } from './textDTDAO';


export interface AwardingProcessDCDAO { 
    pk?: number;
    identifier?: Array<IdentifierDTDAO>;
    description?: TextDTDAO;
    additionalNote?: Array<TextDTDAO>;
    awardingDate?: Date;
    awardingLocation?: LocationDCDAO;
    used?: Array<AssessmentSpecDAO>;
    awardingBody?: Array<OrganizationSpecDAO>;
}
