/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeDTDAO } from './codeDTDAO';
import { IdentifierDTDAO } from './identifierDTDAO';
import { LearningSpecificationDCDAO } from './learningSpecificationDCDAO';
import { OrganizationSpecDAO } from './organizationSpecDAO';


export interface AwardingOpportunityDCDAO { 
    pk?: number;
    identifier?: IdentifierDTDAO;
    awardingBody?: OrganizationSpecDAO;
    location?: CodeDTDAO;
    startedAtTime?: Date;
    endedAtTime?: Date;
    awardedLearningSpecification?: LearningSpecificationDCDAO;
}
