/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TextDTDAO } from './textDTDAO';


export interface CodeDTDAO { 
    pk?: number;
    uri?: string;
    targetName?: TextDTDAO;
    targetDescription?: TextDTDAO;
    targetFrameworkURI?: string;
    targetNotation?: string;
    targetFramework?: TextDTDAO;
}
