/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ConfigView { 
    pk?: string;
    environment?: ConfigView.EnvironmentEnum;
    key?: string;
    value?: string;
}
export namespace ConfigView {
    export type EnvironmentEnum = 'LOCAL' | 'DEV' | 'QA' | 'TEST' | 'ACC' | 'PROD';
    export const EnvironmentEnum = {
        LOCAL: 'LOCAL' as EnvironmentEnum,
        DEV: 'DEV' as EnvironmentEnum,
        QA: 'QA' as EnvironmentEnum,
        TEST: 'TEST' as EnvironmentEnum,
        ACC: 'ACC' as EnvironmentEnum,
        PROD: 'PROD' as EnvironmentEnum
    };
}
