/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDCDAO } from './addressDCDAO';
import { MailboxDCDAO } from './mailboxDCDAO';
import { NoteDTDAO } from './noteDTDAO';
import { PhoneDCDAO } from './phoneDCDAO';
import { WebDocumentDCDAO } from './webDocumentDCDAO';


export interface ContactPointDCDAO { 
    pk?: number;
    note?: Array<NoteDTDAO>;
    description?: NoteDTDAO;
    postalAddress?: Array<AddressDCDAO>;
    phone?: Array<PhoneDCDAO>;
    email?: Array<MailboxDCDAO>;
    contactForm?: Array<WebDocumentDCDAO>;
}
