/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDCView } from './addressDCView';
import { MailboxDCView } from './mailboxDCView';
import { NoteDTView } from './noteDTView';
import { PhoneDCView } from './phoneDCView';
import { WebDocumentDCView } from './webDocumentDCView';


export interface ContactPointDCView { 
    note?: Array<NoteDTView>;
    description?: NoteDTView;
    address?: Array<AddressDCView>;
    phone?: Array<PhoneDCView>;
    emailAddress?: Array<MailboxDCView>;
    contactForm?: Array<WebDocumentDCView>;
}
