/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomizableInstanceFieldView } from './customizableInstanceFieldView';
import { CustomizableInstanceRelationView } from './customizableInstanceRelationView';


export interface CustomizableInstanceView { 
    frontId?: string;
    position?: number;
    order?: number;
    label?: string;
    entityPK?: string;
    fields?: Array<CustomizableInstanceFieldView>;
    relations?: Array<CustomizableInstanceRelationView>;
}
