/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CustomizableInstanceRelationView { 
    frontId?: string;
    position?: number;
    order?: number;
    relPath?: string;
    label?: string;
    groupId?: number;
    groupLabel?: string;
}
