/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomizableFieldView } from './customizableFieldView';
import { CustomizableRelationView } from './customizableRelationView';


export interface CustomizableEntityView { 
    label?: string;
    specClass?: string;
    position?: number;
    fields?: Array<CustomizableFieldView>;
    relations?: Array<CustomizableRelationView>;
}
