/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuditDAO } from './auditDAO';
import { CodeDTDAO } from './codeDTDAO';
import { EscoOccupationAssociationDCDAO } from './escoOccupationAssociationDCDAO';
import { IdentifierDTDAO } from './identifierDTDAO';
import { NoteDTDAO } from './noteDTDAO';
import { OrganizationSpecDAO } from './organizationSpecDAO';
import { TextDTDAO } from './textDTDAO';
import { WebDocumentDCDAO } from './webDocumentDCDAO';


export interface EntitlementSpecDAO { 
    pk?: number;
    languages?: Array<string>;
    defaultTitle?: string;
    defaultLanguage?: string;
    identifier?: Array<IdentifierDTDAO>;
    entitlementType?: CodeDTDAO;
    title?: TextDTDAO;
    alternativeLabel?: Array<TextDTDAO>;
    status?: CodeDTDAO;
    description?: NoteDTDAO;
    additionalNote?: Array<NoteDTDAO>;
    homePage?: Array<WebDocumentDCDAO>;
    supplementaryDocument?: Array<WebDocumentDCDAO>;
    limitOrganization?: Array<OrganizationSpecDAO>;
    limitJurisdiction?: Array<CodeDTDAO>;
    limitOccupation?: Array<EscoOccupationAssociationDCDAO>;
    auditDAO?: AuditDAO;
}
