/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeDTView } from './codeDTView';
import { IdentifierDTView } from './identifierDTView';
import { LearningSpecificationDCView } from './learningSpecificationDCView';
import { NoteDTView } from './noteDTView';
import { TextDTView } from './textDTView';
import { WebDocumentDCView } from './webDocumentDCView';


export interface EntitlemSpecificationDCView { 
    identifier?: Array<IdentifierDTView>;
    dcType?: CodeDTView;
    title?: TextDTView;
    altLabel?: TextDTView;
    status?: CodeDTView;
    description?: NoteDTView;
    additionalNote?: Array<NoteDTView>;
    homePage?: Array<WebDocumentDCView>;
    supplementaryDocument?: Array<WebDocumentDCView>;
    limitJurisdiction?: Array<CodeDTView>;
    limitOccupation?: Array<CodeDTView>;
    limitNationalOccupation?: Array<CodeDTView>;
    mayResultFrom?: Array<LearningSpecificationDCView>;
    hasPart?: Array<EntitlemSpecificationDCView>;
    specialisationOf?: Array<EntitlemSpecificationDCView>;
}
