/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContactPointDCView } from './contactPointDCView';
import { TextDTView } from './textDTView';


export interface GroupDCView { 
    prefLabel: TextDTView;
    contactPoint?: Array<ContactPointDCView>;
}
