/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AwardingOpportunityDCView } from './awardingOpportunityDCView';
import { CodeDTView } from './codeDTView';
import { CreditPointView } from './creditPointView';
import { IdentifierDTView } from './identifierDTView';
import { NoteDTView } from './noteDTView';
import { TextDTView } from './textDTView';
import { WebDocumentDCView } from './webDocumentDCView';


export interface LearningSpecificationDCView { 
    identifier?: Array<IdentifierDTView>;
    learningOpportunityType?: Array<CodeDTView>;
    title?: TextDTView;
    altLabel?: TextDTView;
    definition?: NoteDTView;
    learningOutcomeSummary?: NoteDTView;
    additionalNote?: Array<NoteDTView>;
    homePage?: Array<WebDocumentDCView>;
    supplementaryDocument?: Array<WebDocumentDCView>;
    thematicArea?: Array<CodeDTView>;
    educationSubject?: Array<CodeDTView>;
    volumeOfLearning?: number;
    creditPoints?: Array<CreditPointView>;
    educationLevel?: Array<CodeDTView>;
    language?: Array<CodeDTView>;
    mode?: Array<CodeDTView>;
    learningSetting?: CodeDTView;
    maximumDuration?: number;
    targetGroup?: Array<CodeDTView>;
    entryRequirement?: NoteDTView;
    awardingOpportunity?: Array<AwardingOpportunityDCView>;
    eqfLevel?: CodeDTView;
    nqfLevel?: Array<CodeDTView>;
    nqfLevelParent?: CodeDTView;
    qualificationCode?: Array<CodeDTView>;
    dcType?: Array<CodeDTView>;
    partialQualification?: boolean;
}
