/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuditDAO } from './auditDAO';
import { IdentifierDTDAO } from './identifierDTDAO';
import { LearningAchievementSpecDAO } from './learningAchievementSpecDAO';
import { LearningSpecificationDCDAO } from './learningSpecificationDCDAO';
import { LocationDCDAO } from './locationDCDAO';
import { NoteDTDAO } from './noteDTDAO';
import { OrganizationSpecDAO } from './organizationSpecDAO';
import { TextDTDAO } from './textDTDAO';


export interface LearningActivitySpecDAO { 
    pk?: number;
    languages?: Array<string>;
    defaultTitle?: string;
    defaultLanguage?: string;
    identifier?: Array<IdentifierDTDAO>;
    title?: TextDTDAO;
    description?: NoteDTDAO;
    additionalNote?: Array<NoteDTDAO>;
    workload?: number;
    location?: Array<LocationDCDAO>;
    startedAtTime?: Date;
    endedAtTime?: Date;
    directedBy?: Array<OrganizationSpecDAO>;
    usedLearningOpportunity?: LearningSpecificationDCDAO;
    specifiedBy?: LearningAchievementSpecDAO;
    hasPart?: Array<LearningActivitySpecDAO>;
    influenced?: Array<LearningAchievementSpecDAO>;
    auditDAO?: AuditDAO;
}
