/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuditDAO } from './auditDAO';
import { CodeDTDAO } from './codeDTDAO';
import { EscoSkillAssociationDCDAO } from './escoSkillAssociationDCDAO';
import { IdentifierDTDAO } from './identifierDTDAO';
import { NoteDTDAO } from './noteDTDAO';
import { TextDTDAO } from './textDTDAO';


export interface LearningOutcomeSpecDAO { 
    pk?: number;
    languages?: Array<string>;
    defaultTitle?: string;
    defaultLanguage?: string;
    identifier?: Array<IdentifierDTDAO>;
    name?: TextDTDAO;
    description?: NoteDTDAO;
    learningOutcomeType?: CodeDTDAO;
    reusabilityLevel?: CodeDTDAO;
    relatedESCOSkill?: Array<EscoSkillAssociationDCDAO>;
    auditDAO?: AuditDAO;
}
