/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssessmentSpecDAO } from './assessmentSpecDAO';
import { AwardingOpportunityDCDAO } from './awardingOpportunityDCDAO';
import { CodeDTDAO } from './codeDTDAO';
import { EducationLevelAssociationDTDAO } from './educationLevelAssociationDTDAO';
import { EducationSubjectAssociationDTDAO } from './educationSubjectAssociationDTDAO';
import { EntitlementSpecDAO } from './entitlementSpecDAO';
import { IdentifierDTDAO } from './identifierDTDAO';
import { LearningActivitySpecDAO } from './learningActivitySpecDAO';
import { LearningOutcomeSpecDAO } from './learningOutcomeSpecDAO';
import { NoteDTDAO } from './noteDTDAO';
import { NumericScoreDTDAO } from './numericScoreDTDAO';
import { TextDTDAO } from './textDTDAO';
import { WebDocumentDCDAO } from './webDocumentDCDAO';


export interface LearningSpecificationDCDAO { 
    pk?: number;
    identifier?: Array<IdentifierDTDAO>;
    learningOpportunityType?: Array<CodeDTDAO>;
    title?: TextDTDAO;
    alternativeLabel?: Array<TextDTDAO>;
    definition?: NoteDTDAO;
    learningOutcomeDescription?: NoteDTDAO;
    additionalNote?: Array<NoteDTDAO>;
    homePage?: Array<WebDocumentDCDAO>;
    supplementaryDocument?: Array<WebDocumentDCDAO>;
    educationSubject?: Array<EducationSubjectAssociationDTDAO>;
    volumeOfLearning?: number;
    creditPoints?: Array<NumericScoreDTDAO>;
    educationLevel?: Array<EducationLevelAssociationDTDAO>;
    language?: Array<CodeDTDAO>;
    mode?: Array<CodeDTDAO>;
    learningSetting?: CodeDTDAO;
    maximumDuration?: number;
    targetGroup?: Array<CodeDTDAO>;
    entryRequirementsNote?: NoteDTDAO;
    awardingOpportunity?: Array<AwardingOpportunityDCDAO>;
    learningOutcome?: Array<LearningOutcomeSpecDAO>;
    learningActivitySpecification?: LearningActivitySpecDAO;
    assessmentSpecification?: AssessmentSpecDAO;
    entitlementSpecification?: Array<EntitlementSpecDAO>;
    hasPart?: Array<LearningSpecificationDCDAO>;
    specialisationOf?: Array<LearningSpecificationDCDAO>;
    iscedfcode?: Array<CodeDTDAO>;
    ectscreditPoints?: NumericScoreDTDAO;
}
