/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssessmentSpecDAO } from './assessmentSpecDAO';
import { AuditDAO } from './auditDAO';
import { AwardingProcessDCDAO } from './awardingProcessDCDAO';
import { EntitlementSpecDAO } from './entitlementSpecDAO';
import { IdentifierDTDAO } from './identifierDTDAO';
import { LearningActivitySpecDAO } from './learningActivitySpecDAO';
import { LearningSpecificationDCDAO } from './learningSpecificationDCDAO';
import { NoteDTDAO } from './noteDTDAO';
import { TextDTDAO } from './textDTDAO';


export interface LearningAchievementSpecDAO { 
    pk?: number;
    languages?: Array<string>;
    defaultTitle?: string;
    defaultLanguage?: string;
    identifier?: Array<IdentifierDTDAO>;
    title?: TextDTDAO;
    description?: NoteDTDAO;
    additionalNote?: Array<NoteDTDAO>;
    wasAwardedBy?: AwardingProcessDCDAO;
    associatedLearningOpportunity?: LearningSpecificationDCDAO;
    hasPart?: Array<LearningAchievementSpecDAO>;
    wasInfluencedBy?: Array<LearningActivitySpecDAO>;
    wasDerivedFrom?: Array<AssessmentSpecDAO>;
    entitlesTo?: Array<EntitlementSpecDAO>;
    auditDAO?: AuditDAO;
}
