/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdditionalInfo } from './additionalInfo';
import { IdentifierDTView } from './identifierDTView';
import { LearningActSpecificationDCView } from './learningActSpecificationDCView';
import { LearningSpecificationDCView } from './learningSpecificationDCView';
import { LocationDCView } from './locationDCView';
import { NoteDTView } from './noteDTView';
import { SubresourcesOids } from './subresourcesOids';
import { TextDTView } from './textDTView';


export interface LearningActivitySpecView { 
    oid?: number;
    additionalInfo?: AdditionalInfo;
    displayName?: string;
    label?: string;
    defaultLanguage: string;
    title?: TextDTView;
    identifier?: Array<IdentifierDTView>;
    description?: NoteDTView;
    additionalNote?: Array<NoteDTView>;
    workload?: string;
    location?: Array<LocationDCView>;
    startedAtTime?: string;
    endedAtTime?: string;
    usedLearningOpportunity?: LearningSpecificationDCView;
    specifiedBy?: LearningActSpecificationDCView;
    relDirectedBy?: SubresourcesOids;
    relInfluenced?: SubresourcesOids;
    relHasPart?: SubresourcesOids;
}
