/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDCDAO } from './addressDCDAO';
import { CodeDTDAO } from './codeDTDAO';
import { IdentifierDTDAO } from './identifierDTDAO';
import { NoteDTDAO } from './noteDTDAO';
import { TextDTDAO } from './textDTDAO';


export interface LocationDCDAO { 
    pk?: number;
    identifier?: Array<IdentifierDTDAO>;
    geographicName?: TextDTDAO;
    spatialCode?: Array<CodeDTDAO>;
    description?: NoteDTDAO;
    hasAddress?: Array<AddressDCDAO>;
}
