/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDCView } from './addressDCView';
import { CodeDTView } from './codeDTView';
import { IdentifierDTView } from './identifierDTView';
import { NoteDTView } from './noteDTView';
import { TextDTView } from './textDTView';


export interface LocationDCView { 
    identifier?: Array<IdentifierDTView>;
    geographicName?: TextDTView;
    spatialCode?: Array<CodeDTView>;
    description?: NoteDTView;
    hasAddress?: Array<AddressDCView>;
}
