/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeDTView } from './codeDTView';


export interface MediaObjectDTView { 
    contentType?: CodeDTView;
    contentEncoding?: CodeDTView;
    contentSize?: number;
    content?: string;
    contentUrl?: string;
}
