/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InputStream } from './inputStream';


export interface MultipartFile { 
    contentType?: string;
    originalFilename?: string;
    name?: string;
    empty?: boolean;
    bytes?: Array<string>;
    size?: number;
    inputStream?: InputStream;
}
