/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeDTView } from './codeDTView';
import { ContentDTView } from './contentDTView';


export interface NoteDTView { 
    contents?: Array<ContentDTView>;
    subject?: CodeDTView;
    moreInformation?: boolean;
}
