/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccreditationDCView } from './accreditationDCView';
import { AdditionalInfo } from './additionalInfo';
import { CodeDTView } from './codeDTView';
import { ContactPointDCView } from './contactPointDCView';
import { IdentifierDTView } from './identifierDTView';
import { LegalIdentifierDTView } from './legalIdentifierDTView';
import { LocationDCView } from './locationDCView';
import { MediaObjectDTView } from './mediaObjectDTView';
import { NoteDTView } from './noteDTView';
import { SubresourcesOids } from './subresourcesOids';
import { TextDTView } from './textDTView';
import { WebDocumentDCView } from './webDocumentDCView';


export interface OrganizationSpecView { 
    oid?: number;
    additionalInfo?: AdditionalInfo;
    defaultTitle: string;
    defaultLanguage: string;
    preferredName?: TextDTView;
    vatIdentifier?: Array<LegalIdentifierDTView>;
    taxIdentifier?: Array<LegalIdentifierDTView>;
    homePage?: Array<WebDocumentDCView>;
    hasAccreditation?: Array<AccreditationDCView>;
    logo?: MediaObjectDTView;
    identifier?: Array<IdentifierDTView>;
    type?: Array<CodeDTView>;
    legalIdentifier: IdentifierDTView;
    alternativeName?: Array<TextDTView>;
    note?: Array<NoteDTView>;
    relUnitOf?: SubresourcesOids;
    hasLocation: Array<LocationDCView>;
    contactPoint?: Array<ContactPointDCView>;
}
