/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LearningActivitySpecLiteView } from './learningActivitySpecLiteView';
import { Link } from './link';
import { PageMetadata } from './pageMetadata';


export interface PagedResourcesLearningActivitySpecLiteView { 
    readonly links?: Array<Link>;
    readonly content?: Array<LearningActivitySpecLiteView>;
    readonly page?: PageMetadata;
}
