/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdditionalInfo } from './additionalInfo';
import { AssessmSpecificationDCView } from './assessmSpecificationDCView';
import { AwardingProcessDCView } from './awardingProcessDCView';
import { CodeDTView } from './codeDTView';
import { IdentifierDTView } from './identifierDTView';
import { Link } from './link';
import { LocationDCView } from './locationDCView';
import { NoteDTView } from './noteDTView';
import { ResultDistributionDTView } from './resultDistributionDTView';
import { ShortenedGradingDTView } from './shortenedGradingDTView';
import { SubresourcesOids } from './subresourcesOids';
import { TextDTView } from './textDTView';


export interface ResourceAssessmentSpecView { 
    oid?: number;
    additionalInfo?: AdditionalInfo;
    displayName?: string;
    label?: string;
    defaultLanguage: string;
    title: TextDTView;
    identifier?: Array<IdentifierDTView>;
    description?: TextDTView;
    additionalNote?: Array<NoteDTView>;
    grade?: NoteDTView;
    shortenedGrading?: ShortenedGradingDTView;
    resultDistribution?: ResultDistributionDTView;
    dateIssued?: string;
    idVerification?: CodeDTView;
    awardedBy?: AwardingProcessDCView;
    location?: LocationDCView;
    specifiedBy?: AssessmSpecificationDCView;
    relHasPart?: SubresourcesOids;
    relAssessedBy?: SubresourcesOids;
    relAwardingBody?: SubresourcesOids;
    readonly links?: Array<Link>;
}
