/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdditionalInfo } from './additionalInfo';
import { AwardingProcessDCView } from './awardingProcessDCView';
import { IdentifierDTView } from './identifierDTView';
import { LearningSpecificationDCView } from './learningSpecificationDCView';
import { Link } from './link';
import { NoteDTView } from './noteDTView';
import { SubresourcesOids } from './subresourcesOids';
import { TextDTView } from './textDTView';


export interface ResourceLearningAchievementSpecView { 
    oid?: number;
    additionalInfo?: AdditionalInfo;
    displayName?: string;
    label?: string;
    defaultLanguage: string;
    title: TextDTView;
    identifier?: Array<IdentifierDTView>;
    description?: NoteDTView;
    additionalNote?: Array<NoteDTView>;
    wasAwardedBy?: AwardingProcessDCView;
    specifiedBy?: LearningSpecificationDCView;
    relAwardingBody?: SubresourcesOids;
    relProvenBy?: SubresourcesOids;
    relInfluencedBy?: SubresourcesOids;
    relEntitlesTo?: SubresourcesOids;
    relSubAchievements?: SubresourcesOids;
    relLearningOutcomes?: SubresourcesOids;
    readonly links?: Array<Link>;
}
