/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomizableInstanceView } from './customizableInstanceView';
import { Link } from './link';


export interface ResourceCustomizableInstanceSpecView { 
    customizableInstanceViews?: Array<CustomizableInstanceView>;
    readonly links?: Array<Link>;
}
