/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NoteDTView } from './noteDTView';
import { ScoreDTView } from './scoreDTView';
import { TextDTView } from './textDTView';


export interface ResultCategoryDTView { 
    category?: Array<ResultCategoryDTView>;
    label?: TextDTView;
    score?: ScoreDTView;
    minScore?: ScoreDTView;
    maxScore?: ScoreDTView;
    count?: number;
    description?: NoteDTView;
}
