/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CredentialView } from './credentialView';
import { DSSTimestampDTO } from './dSSTimestampDTO';
import { SignatureNexuFeedbackView } from './signatureNexuFeedbackView';
import { SignatureNexuResponseView } from './signatureNexuResponseView';


export interface SignatureNexuView { 
    presentation?: string;
    success?: string;
    uuid?: string;
    response?: SignatureNexuResponseView;
    feedback?: SignatureNexuFeedbackView;
    credential?: CredentialView;
    date?: Date;
    dssTimestampDTO?: DSSTimestampDTO;
}
