/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AttachmentView } from './attachmentView';
import { SignatureParametersFeedbackView } from './signatureParametersFeedbackView';
import { SignatureParametersResponseView } from './signatureParametersResponseView';


export interface SignatureParametersView { 
    presentation?: string;
    success?: string;
    uuids?: Array<string>;
    response?: SignatureParametersResponseView;
    feedback?: SignatureParametersFeedbackView;
    mandatedIssue?: AttachmentView;
}
