/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContentDTDAO } from './contentDTDAO';


export interface TextDTDAO { 
    pk?: number;
    extra?: string;
    contents?: Array<ContentDTDAO>;
    contentsNewInstance?: ContentDTDAO;
    anyLanguageString?: string;
    stringContent?: string;
}
