UPDATE CREDENTIAL_LOCALIZABLE_INFO C SET C.CRED_ID = (SELECT C2.CREDENTIAL_CRED_ID
    FROM CREDENTIAL_T_CREDENTIAL_LOCALIZABLE_INFO C2 WHERE C.PK = C2.credentialLocalizableInfo_PK) WHERE C.CRED_ID IS NULL;

update credential_localizable_info set CREDENTIAL_TYPE = 'Converted' where CREDENTIAL_TYPE is null;

DROP TABLE CREDENTIAL_T_CREDENTIAL_LOCALIZABLE_INFO;

