export const environment = {
    production: false,
    serviceWorker: true,
    enableDevToolRedux: true,
    hasLabelsOnly: true,
    viewerBaseUrl: window['EDCIContext'].viewerBaseUrl,
    apiBaseUrl: 'http://localhost:8080/europass2/edci-viewer',
    issuerBaseUrl: 'http://localhost:8080/europass2/edci-issuer',
    walletBaseUrl: 'http://localhost:8080/europass2/edci-wallet',
    europassRoot: 'https://webgate.acceptance.ec.europa.eu/europass',
    ePortfolioUrl:
        // tslint:disable-next-line: max-line-length
        'https://webgate.acceptance.ec.europa.eu/europass/eportfolio/api/europass-auth/authenticate?redirect_uri=https://webgate.acceptance.ec.europa.eu/d/empl/europass/',
    downloadCredentialUrl: '/api/v1/credentials/{walletAddress}/verifiable',
    walletAddressParameter: '{walletAddress}',
    downloadSharedCredentialUrl: '/api/v1/sharelinks/{shareHash}/presentation',
    shareHashParameter: '{shareHash}',
    loginUrl: '/auth/oidc/eulogin',
    logoutUrl: '/auth/oidc/eulogin/logout',
    csrfEnabled: true,
    isMockUser: true,
    hasBranding: false,
    headerImagePath: '',
    homeMainTitle: 'translated.label.homeMainTitle',
    homeMainDescription: 'translated.label.homeMainDescription',
    homeMenuMainTitle: 'translated.label.homeMenuMainTitle',
    homeMenuDescription: 'translated.label.homeMenuDescription',
};
