CREATE TABLE TEMP_DATA (ACHIVEMENT_PK, DESCRIPTION_PK, DESCRIPTION_TEXT_PK)
  AS (SELECT PK, DESCRIPTION_PK, DT_TEXT_SEQ.nextval from SPEC_LEARNING_ACHIEVEMENT where DESCRIPTION_PK is not null);

INSERT INTO DT_TEXT (PK)
    Select TEMP.DESCRIPTION_TEXT_PK from TEMP_DATA TEMP;

INSERT INTO FIELD_DT_TEXT_CONTENTS (
    Select TEMP.DESCRIPTION_TEXT_PK, text.dt_cont_pk from FIELD_DT_NOTE_CONTENTS TEXT JOIN TEMP_DATA TEMP ON TEXT.DT_NOTE_PK = TEMP.DESCRIPTION_PK
);

DELETE FROM FIELD_DT_NOTE_CONTENTS WHERE DT_NOTE_PK in (select DESCRIPTION_PK from TEMP_DATA);

merge into SPEC_LEARNING_ACHIEVEMENT
using TEMP_DATA
on (SPEC_LEARNING_ACHIEVEMENT.PK = TEMP_DATA.ACHIVEMENT_PK)
when matched then update
set DESCRIPTION_TEXT_PK = TEMP_DATA.DESCRIPTION_TEXT_PK;

-- Delete already migrated registers
alter table SPEC_LEARNING_ACHIEVEMENT drop column DESCRIPTION_PK;

DROP TABLE TEMP_DATA;