CREATE TABLE TEMP_DATA (ACTIVITY_PK, DESCRIPTION_PK, DESCRIPTION_TEXT_PK)
  AS (SELECT PK, DECRIPTION_PK, DT_TEXT_SEQ.nextval from SPEC_ACTIVITY where DECRIPTION_PK is not null);

INSERT INTO DT_TEXT (PK)
    Select TEMP.DESCRIPTION_TEXT_PK from TEMP_DATA TEMP;

INSERT INTO FIELD_DT_TEXT_CONTENTS (
    Select TEMP.DESCRIPTION_TEXT_PK, text.dt_cont_pk from FIELD_DT_NOTE_CONTENTS TEXT JOIN TEMP_DATA TEMP ON TEXT.DT_NOTE_PK = TEMP.DESCRIPTION_PK
);

DELETE FROM FIELD_DT_NOTE_CONTENTS WHERE DT_NOTE_PK in (select DESCRIPTION_PK from TEMP_DATA);

merge into SPEC_ACTIVITY
using TEMP_DATA
on (SPEC_ACTIVITY.PK = TEMP_DATA.ACTIVITY_PK)
when matched then update
set DESCRIPTION_TEXT_PK = TEMP_DATA.DESCRIPTION_TEXT_PK;

-- Delete already migrated registers
alter table SPEC_ACTIVITY drop column DECRIPTION_PK;

DROP TABLE TEMP_DATA;