merge into SPEC_ORGANIZATION
using (select SPEC_ORGAN_PK, min(DT_TEXT_PK) as DT_TEXT_PK from FIELD_SPEC_ORGAN_ALTER_NAME group by SPEC_ORGAN_PK) ALTER_NAME
on (SPEC_ORGANIZATION.PK = ALTER_NAME.SPEC_ORGAN_PK)
when matched then update
set ALTERNATIVE_NAME_PK = ALTER_NAME.DT_TEXT_PK;

DROP TABLE FIELD_SPEC_ORGAN_ALTER_NAME;