/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Code } from './code';
import { Identifier } from './identifier';
import { Note } from './note';
import { OrganizationDTO } from './organizationDTO';
import { QualificationDTO } from './qualificationDTO';
import { Score } from './score';
import { Text } from './text';
import { WebDocumentDTO } from './webDocumentDTO';


export interface AccreditationDTO { 
    id?: string;
    pk?: string;
    identifier?: Array<Identifier>;
<<<<<<< HEAD
    accreditationType?: Code;
=======
    accreditationType: Code;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
    title?: Text;
    description?: Note;
    decision?: Score;
    report?: WebDocumentDTO;
<<<<<<< HEAD
    organization?: OrganizationDTO;
=======
    organization: OrganizationDTO;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
    limitQualification?: QualificationDTO;
    limitField?: Array<Code>;
    limitEqfLevel?: Array<Code>;
    limitJurisdiction?: Array<Code>;
<<<<<<< HEAD
    accreditingAgent?: OrganizationDTO;
=======
    accreditingAgent: OrganizationDTO;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
    issueDate?: Date;
    reviewDate?: Date;
    expiryDate?: Date;
    additionalNote?: Array<Note>;
    homePage?: Array<WebDocumentDTO>;
    supplementaryDocument?: Array<WebDocumentDTO>;
    identifiableName?: string;
}
