/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Code } from './code';
import { ContactPoint } from './contactPoint';
import { Identifier } from './identifier';
import { LocationDTO } from './locationDTO';
import { Note } from './note';
import { Text } from './text';


export interface AgentDTO { 
    id?: string;
    identifier?: Array<Identifier>;
    type?: Array<Code>;
    preferredName?: Text;
    alternativeName?: Array<Text>;
    note?: Array<Note>;
    hasLocation?: Array<LocationDTO>;
    contactPoint?: Array<ContactPoint>;
    identifiableName?: string;
}
