/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Amount { 
<<<<<<< HEAD
    content?: number;
    unit?: string;
=======
    content: number;
    unit: string;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
}
