/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssessmentSpecificationDTO } from './assessmentSpecificationDTO';
import { Code } from './code';
import { Identifier } from './identifier';
import { Note } from './note';
import { OrganizationDTO } from './organizationDTO';
import { ResultDistributionDTO } from './resultDistributionDTO';
import { Score } from './score';
import { ShortenedGradingDTO } from './shortenedGradingDTO';
import { Text } from './text';


export interface AssessmentDTO { 
    pk?: string;
<<<<<<< HEAD
    id?: string;
    identifier?: Array<Identifier>;
    title?: Text;
    description?: Text;
    additionalNote?: Array<Note>;
    grade?: Score;
=======
    id: string;
    identifier?: Array<Identifier>;
    title: Text;
    description?: Text;
    additionalNote?: Array<Note>;
    grade: Score;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
    shortenedGrading?: ShortenedGradingDTO;
    resultDistribution?: ResultDistributionDTO;
    issuedDate?: Date;
    idVerification?: Code;
    specifiedBy?: AssessmentSpecificationDTO;
    hasPart?: Array<AssessmentDTO>;
    assessedBy?: Array<OrganizationDTO>;
    identifiableName?: string;
}
