/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Code } from './code';
import { Identifier } from './identifier';
import { LearningSpecificationDTO } from './learningSpecificationDTO';
import { OrganizationDTO } from './organizationDTO';


export interface AwardingOpportunityDTO { 
<<<<<<< HEAD
    id?: string;
    identifier?: Array<Identifier>;
    awardedLearningSpecification?: LearningSpecificationDTO;
=======
    id: string;
    identifier?: Array<Identifier>;
    awardedLearningSpecification: LearningSpecificationDTO;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
    awardingBody?: Array<OrganizationDTO>;
    location?: Code;
    startDate?: Date;
    endDate?: Date;
    identifiableName?: string;
}
