/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InputStream } from './inputStream';


export interface ByteArrayResource { 
    byteArray?: Array<string>;
    description?: string;
    inputStream?: InputStream;
    url?: string;
    file?: Blob;
    open?: boolean;
    uri?: string;
    readable?: boolean;
    filename?: string;
}
