/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RevocationWrapper } from './revocationWrapper';
import { TrustedServiceWrapper } from './trustedServiceWrapper';
import { XmlChainItem } from './xmlChainItem';
import { XmlDigestAlgoAndValue } from './xmlDigestAlgoAndValue';
import { XmlDigestMatcher } from './xmlDigestMatcher';
import { XmlOID } from './xmlOID';
import { XmlTrustedServiceProvider } from './xmlTrustedServiceProvider';


export interface CertificateWrapper { 
    id?: string;
    state?: string;
    trusted?: boolean;
    email?: string;
<<<<<<< HEAD
    certificateTSPServiceExpiredCertsRevocationInfo?: Date;
    commonName?: string;
    serialNumber?: string;
    countryName?: string;
    certificateDN?: string;
    binaries?: Array<string>;
    revoked?: boolean;
    surname?: string;
    qctypes?: Array<string>;
    givenName?: string;
    locality?: string;
    pseudo?: string;
    keyUsages?: Array<string>;
    cpsUrls?: Array<string>;
    notAfter?: Date;
    notBefore?: Date;
    policyIds?: Array<string>;
    selfSigned?: boolean;
    revocationData?: Array<RevocationWrapper>;
    certificateIssuerDN?: string;
    revocationDataAvailable?: boolean;
    validCertificate?: boolean;
    latestRevocationData?: RevocationWrapper;
    idKpOCSPSigning?: boolean;
    idPkixOcspNoCheck?: boolean;
    organizationName?: string;
    organizationalUnit?: string;
    digestAlgoAndValues?: Array<XmlDigestAlgoAndValue>;
    trustServiceProviders?: Array<XmlTrustedServiceProvider>;
    trustedServices?: Array<TrustedServiceWrapper>;
    trustedListCountryCodes?: Array<string>;
    crldistributionPoints?: Array<string>;
    extendedKeyUsages?: Array<XmlOID>;
    qcstatementIds?: Array<string>;
    ocspaccessUrls?: Array<string>;
    authorityInformationAccessUrls?: Array<string>;
    signatureValid?: boolean;
    certificateChain?: Array<XmlChainItem>;
    digestAlgorithm?: CertificateWrapper.DigestAlgorithmEnum;
    trustedChain?: boolean;
    signingCertificateId?: string;
    certificateChainIds?: Array<string>;
    encryptionAlgorithm?: CertificateWrapper.EncryptionAlgorithmEnum;
    maskGenerationFunction?: CertificateWrapper.MaskGenerationFunctionEnum;
    digestMatchers?: Array<XmlDigestMatcher>;
    digestValuePresent?: boolean;
    keyLengthUsedToSignThisToken?: string;
    firstChainCertificateId?: string;
    signatureIntact?: boolean;
    lastChainCertificateId?: string;
    issuerSerialMatch?: boolean;
    firstChainCertificate?: XmlChainItem;
    digestValueMatch?: boolean;
    digestAlgoUsedToSignThisToken?: string;
    lastChainCertificateSource?: string;
    lastChainCertificate?: XmlChainItem;
    attributePresent?: boolean;
    encryptionAlgoUsedToSignThisToken?: string;
    maskGenerationFunctionUsedToSignThisToken?: string;
=======
    commonName?: string;
    certificateTSPServiceExpiredCertsRevocationInfo?: Date;
    binaries?: Array<string>;
    countryName?: string;
    keyUsages?: Array<string>;
    revoked?: boolean;
    selfSigned?: boolean;
    notBefore?: Date;
    notAfter?: Date;
    cpsUrls?: Array<string>;
    qctypes?: Array<string>;
    locality?: string;
    surname?: string;
    policyIds?: Array<string>;
    givenName?: string;
    pseudo?: string;
    certificateDN?: string;
    serialNumber?: string;
    certificateIssuerDN?: string;
    validCertificate?: boolean;
    latestRevocationData?: RevocationWrapper;
    revocationDataAvailable?: boolean;
    revocationData?: Array<RevocationWrapper>;
    idKpOCSPSigning?: boolean;
    organizationalUnit?: string;
    trustedListCountryCodes?: Array<string>;
    ocspaccessUrls?: Array<string>;
    idPkixOcspNoCheck?: boolean;
    trustServiceProviders?: Array<XmlTrustedServiceProvider>;
    extendedKeyUsages?: Array<XmlOID>;
    digestAlgoAndValues?: Array<XmlDigestAlgoAndValue>;
    organizationName?: string;
    qcstatementIds?: Array<string>;
    trustedServices?: Array<TrustedServiceWrapper>;
    crldistributionPoints?: Array<string>;
    authorityInformationAccessUrls?: Array<string>;
    certificateChain?: Array<XmlChainItem>;
    digestAlgorithm?: CertificateWrapper.DigestAlgorithmEnum;
    trustedChain?: boolean;
    signatureValid?: boolean;
    signingCertificateId?: string;
    certificateChainIds?: Array<string>;
    maskGenerationFunction?: CertificateWrapper.MaskGenerationFunctionEnum;
    digestMatchers?: Array<XmlDigestMatcher>;
    encryptionAlgorithm?: CertificateWrapper.EncryptionAlgorithmEnum;
    lastChainCertificate?: XmlChainItem;
    digestValueMatch?: boolean;
    issuerSerialMatch?: boolean;
    signatureIntact?: boolean;
    keyLengthUsedToSignThisToken?: string;
    attributePresent?: boolean;
    digestValuePresent?: boolean;
    lastChainCertificateId?: string;
    firstChainCertificateId?: string;
    digestAlgoUsedToSignThisToken?: string;
    lastChainCertificateSource?: string;
    firstChainCertificate?: XmlChainItem;
    maskGenerationFunctionUsedToSignThisToken?: string;
    encryptionAlgoUsedToSignThisToken?: string;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
}
export namespace CertificateWrapper {
    export type DigestAlgorithmEnum = 'SHA1' | 'SHA224' | 'SHA256' | 'SHA384' | 'SHA512' | 'SHA3_224' | 'SHA3_256' | 'SHA3_384' | 'SHA3_512' | 'RIPEMD160' | 'MD2' | 'MD5';
    export const DigestAlgorithmEnum = {
        SHA1: 'SHA1' as DigestAlgorithmEnum,
        SHA224: 'SHA224' as DigestAlgorithmEnum,
        SHA256: 'SHA256' as DigestAlgorithmEnum,
        SHA384: 'SHA384' as DigestAlgorithmEnum,
        SHA512: 'SHA512' as DigestAlgorithmEnum,
        SHA3224: 'SHA3_224' as DigestAlgorithmEnum,
        SHA3256: 'SHA3_256' as DigestAlgorithmEnum,
        SHA3384: 'SHA3_384' as DigestAlgorithmEnum,
        SHA3512: 'SHA3_512' as DigestAlgorithmEnum,
        RIPEMD160: 'RIPEMD160' as DigestAlgorithmEnum,
        MD2: 'MD2' as DigestAlgorithmEnum,
        MD5: 'MD5' as DigestAlgorithmEnum
    };
<<<<<<< HEAD
=======
    export type MaskGenerationFunctionEnum = 'MGF1';
    export const MaskGenerationFunctionEnum = {
        MGF1: 'MGF1' as MaskGenerationFunctionEnum
    };
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
    export type EncryptionAlgorithmEnum = 'RSA' | 'DSA' | 'ECDSA' | 'PLAIN_ECDSA' | 'HMAC';
    export const EncryptionAlgorithmEnum = {
        RSA: 'RSA' as EncryptionAlgorithmEnum,
        DSA: 'DSA' as EncryptionAlgorithmEnum,
        ECDSA: 'ECDSA' as EncryptionAlgorithmEnum,
        PLAINECDSA: 'PLAIN_ECDSA' as EncryptionAlgorithmEnum,
        HMAC: 'HMAC' as EncryptionAlgorithmEnum
    };
<<<<<<< HEAD
    export type MaskGenerationFunctionEnum = 'MGF1';
    export const MaskGenerationFunctionEnum = {
        MGF1: 'MGF1' as MaskGenerationFunctionEnum
    };
=======
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
}
