/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDTO } from './addressDTO';
import { InteractiveWebResourceDTO } from './interactiveWebResourceDTO';
import { MailboxDTO } from './mailboxDTO';
import { Note } from './note';
import { PhoneDTO } from './phoneDTO';


export interface ContactPoint { 
    note?: Array<Note>;
    description?: Note;
    postalAddress?: Array<AddressDTO>;
    phone?: Array<PhoneDTO>;
    email?: Array<MailboxDTO>;
    walletAddress?: Array<string>;
    contactForm?: Array<InteractiveWebResourceDTO>;
<<<<<<< HEAD
=======
    identifiableName?: string;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
}
