/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EntitlementSpecificationDTO } from './entitlementSpecificationDTO';
import { Identifier } from './identifier';
import { LearningAchievementDTO } from './learningAchievementDTO';
import { Note } from './note';
import { Text } from './text';


export interface EntitlementDTO { 
<<<<<<< HEAD
    id?: string;
    identifier?: Array<Identifier>;
    title?: Text;
=======
    id: string;
    identifier?: Array<Identifier>;
    title: Text;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
    description?: Note;
    issuedDate?: Date;
    expiryDate?: Date;
    additionalNote?: Array<Note>;
    specifiedBy?: EntitlementSpecificationDTO;
    wasDerivedFrom?: Array<LearningAchievementDTO>;
    hasPart?: Array<EntitlementDTO>;
    identifiableName?: string;
}
