/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccreditationDTO } from './accreditationDTO';
import { AssessmentSpecificationDTO } from './assessmentSpecificationDTO';
import { Code } from './code';
import { DisplayParametersDTO } from './displayParametersDTO';
import { EntitlementSpecificationDTO } from './entitlementSpecificationDTO';
import { Identifier } from './identifier';
import { LearningActivitySpecificationDTO } from './learningActivitySpecificationDTO';
import { LearningOpportunityDTO } from './learningOpportunityDTO';
import { LearningSpecificationDTO } from './learningSpecificationDTO';
import { MediaObject } from './mediaObject';
import { Note } from './note';
import { OrganizationDTO } from './organizationDTO';
import { PersonDTO } from './personDTO';
import { ScoringSchemeDTO } from './scoringSchemeDTO';
import { Text } from './text';


export interface EuropassCredentialDTO { 
    valid?: boolean;
    sealed?: boolean;
    validationErrors?: Array<string>;
<<<<<<< HEAD
    id?: string;
    issued?: Date;
    issuanceDate?: Date;
    expirationDate?: Date;
    identifier?: Array<Identifier>;
    type?: Code;
    title?: Text;
    description?: Note;
    issuer?: OrganizationDTO;
    credentialSubject?: PersonDTO;
=======
    id: string;
    issued: Date;
    issuanceDate: Date;
    expirationDate?: Date;
    identifier?: Array<Identifier>;
    type: Code;
    title: Text;
    description?: Note;
    issuer: OrganizationDTO;
    credentialSubject: PersonDTO;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
    subCredentials?: Array<EuropassCredentialDTO>;
    proof?: string;
    display?: DisplayParametersDTO;
    contains?: Array<MediaObject>;
    subCredentialsXML?: Array<string>;
    attachment?: Array<MediaObject>;
    originalXML?: string;
    learningSpecificationReferences?: Array<LearningSpecificationDTO>;
    learningActivitySpecificationReferences?: Array<LearningActivitySpecificationDTO>;
    assessmentSpecificationReferences?: Array<AssessmentSpecificationDTO>;
    entitlementSpecificationReferences?: Array<EntitlementSpecificationDTO>;
    learningOpportunityReferences?: Array<LearningOpportunityDTO>;
    organisationReferences?: Array<OrganizationDTO>;
    accreditationReferences?: Array<AccreditationDTO>;
    scoringSchemeReferences?: Array<ScoringSchemeDTO>;
    identifiableName?: string;
}
