/**
* Wallet API
* API Wallet description
*
* OpenAPI spec version: 1.0.0
* Contact: edci.support@eu.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
import{Code}from'./code';
import {Identifier} from './identifier';
import { LearningSpecificationDTO}from './learningSpecificationDTO';
import {LocationDTO}from './locationDTO';
import {Note}from './note';
import {OrganizationDTO}from './organizationDTO';
import {Period} from './period';
import { PriceDetailsDTO}from './priceDetailsDTO';
import {Text}from './text';
import {WebDocumentDTO}from './webDocumentDTO';


export interface LearningOpportunityDTO {
<<<<<<< HEAD
id?: string;
identifier?: Array< Identifier>;
title?: Text;
=======
id: string;
identifier?: Array < Identifier>;
title: Text;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
altLabel?: Array <Text>;
description?: Note;
additionalNote?: Array < Note>;
homePage?: Array < WebDocumentDTO>;
supplementaryDocument?: Array < WebDocumentDTO>;
startedAtDate?: Date;
endedAtDate?: Date;
duration?: Period;
providedBy?: Array <OrganizationDTO>;
providedAt?: Array < LocationDTO>;
learningSchedule?: Code;
scheduleInformation?: Note;
admissionProcedure?: Note;
priceDetails?: Array < PriceDetailsDTO>;
<<<<<<< HEAD
specifiedBy?: LearningSpecificationDTO;
=======
specifiedBy: LearningSpecificationDTO;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
hasPart?: Array< LearningOpportunityDTO>;
identifiableName?: string;
}
