/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Code } from './code';
<<<<<<< HEAD
import { EscoSkillAssociationDTO } from './escoSkillAssociationDTO';
=======
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
import { Identifier } from './identifier';
import { Note } from './note';
import { Text } from './text';


export interface LearningOutcomeDTO { 
<<<<<<< HEAD
    id?: string;
    identifier?: Array<Identifier>;
    name?: Text;
    description?: Note;
    learningOutcomeType?: Code;
    reusabilityLevel?: Code;
    relatedESCOSkill?: Array<EscoSkillAssociationDTO>;
=======
    id: string;
    identifier?: Array<Identifier>;
    name: Text;
    description?: Note;
    learningOutcomeType?: Code;
    reusabilityLevel?: Code;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
    identifiableName?: string;
}
