/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssessmentDTO } from './assessmentDTO';
import { AwardingProcessDTO } from './awardingProcessDTO';
import { EntitlementDTO } from './entitlementDTO';
import { Identifier } from './identifier';
import { LearningActivityDTO } from './learningActivityDTO';
import { LearningSpecificationDTO } from './learningSpecificationDTO';
import { Note } from './note';
import { Text } from './text';


export interface LearningAchievementDTO { 
<<<<<<< HEAD
    id?: string;
    identifier?: Array<Identifier>;
    title?: Text;
=======
    id: string;
    identifier?: Array<Identifier>;
    title: Text;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
    description?: Note;
    additionalNote?: Array<Note>;
    wasDerivedFrom?: Array<AssessmentDTO>;
    wasInfluencedBy?: Array<LearningActivityDTO>;
    entitlesTo?: Array<EntitlementDTO>;
    wasAwardedBy?: AwardingProcessDTO;
    hasPart?: Array<LearningAchievementDTO>;
<<<<<<< HEAD
    specifiedBy?: LearningSpecificationDTO;
=======
    specifiedBy: LearningSpecificationDTO;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
    identifiableName?: string;
}
