/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Identifier } from './identifier';
import { LearningAchievementDTO } from './learningAchievementDTO';
import { LearningActivitySpecificationDTO } from './learningActivitySpecificationDTO';
import { LocationDTO } from './locationDTO';
import { Note } from './note';
import { OrganizationDTO } from './organizationDTO';
import { Period } from './period';
import { Text } from './text';


export interface LearningActivityDTO { 
<<<<<<< HEAD
    id?: string;
    identifier?: Array<Identifier>;
    title?: Text;
=======
    id: string;
    identifier?: Array<Identifier>;
    title: Text;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
    description?: Note;
    additionalNote?: Array<Note>;
    workload?: Period;
    startedAtTime?: Date;
    endedAtTime?: Date;
    directedBy?: Array<OrganizationDTO>;
    location?: Array<LocationDTO>;
<<<<<<< HEAD
    specifiedBy?: LearningActivitySpecificationDTO;
=======
    specifiedBy: LearningActivitySpecificationDTO;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
    hasPart?: Array<LearningActivityDTO>;
    influenced?: Array<LearningAchievementDTO>;
    identifiableName?: string;
}
