/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Code } from './code';
import { Identifier } from './identifier';
import { LearningSpecificationDTO } from './learningSpecificationDTO';
import { Note } from './note';
import { Period } from './period';
import { Text } from './text';
import { WebDocumentDTO } from './webDocumentDTO';


export interface LearningActivitySpecificationDTO { 
<<<<<<< HEAD
    id?: string;
=======
    id: string;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
    pk?: string;
    identifier?: Array<Identifier>;
    learningActivityType?: Array<Code>;
    title?: Text;
    alternativeLabel?: Array<Text>;
    description?: Note;
    additionalNote?: Array<Note>;
    homePage?: Array<WebDocumentDTO>;
    supplementaryDocument?: Array<WebDocumentDTO>;
    workload?: Period;
    language?: Array<Code>;
    mode?: Code;
    teaches?: Array<LearningSpecificationDTO>;
    hasPart?: Array<LearningActivitySpecificationDTO>;
    specializationOf?: Array<LearningActivitySpecificationDTO>;
    identifiableName?: string;
}
