/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDTO } from './addressDTO';
import { Code } from './code';
import { Identifier } from './identifier';
import { Note } from './note';
import { Text } from './text';


export interface LocationDTO { 
    id?: string;
    identifier?: Array<Identifier>;
    geographicName?: Text;
    spatialCode?: Array<Code>;
    description?: Note;
    hasAddress?: Array<AddressDTO>;
    identifiableName?: string;
}
