/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Organization { 
    id?: string;
    legalIdentifier?: string;
    vatIdentifier?: string;
    taxIdentifier?: string;
    identifier?: string;
    preferredName?: string;
    alternativeName?: string;
    homePage?: string;
    escoOrganizationType?: string;
    email?: string;
    siteLocation?: string;
}
