/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccreditationDTO } from './accreditationDTO';
import { Code } from './code';
import { ContactPoint } from './contactPoint';
import { Identifier } from './identifier';
import { LegalIdentifier } from './legalIdentifier';
import { LocationDTO } from './locationDTO';
import { MediaObject } from './mediaObject';
import { Note } from './note';
import { Text } from './text';
import { WebDocumentDTO } from './webDocumentDTO';


export interface OrganizationDTO { 
<<<<<<< HEAD
    id?: string;
    identifier?: Array<Identifier>;
    type?: Array<Code>;
    preferredName?: Text;
    alternativeName?: Array<Text>;
    note?: Array<Note>;
    hasLocation?: Array<LocationDTO>;
    contactPoint?: Array<ContactPoint>;
    legalIdentifier?: LegalIdentifier;
=======
    id: string;
    identifier?: Array<Identifier>;
    type?: Array<Code>;
    note?: Array<Note>;
    contactPoint?: Array<ContactPoint>;
    preferredName: Text;
    alternativeName?: Array<Text>;
    hasLocation?: Array<LocationDTO>;
    legalIdentifier: LegalIdentifier;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
    vatIdentifier?: Array<LegalIdentifier>;
    taxIdentifier?: Array<LegalIdentifier>;
    homepage?: Array<WebDocumentDTO>;
    hasAccreditation?: Array<AccreditationDTO>;
    hasUnit?: Array<OrganizationDTO>;
    unitOf?: OrganizationDTO;
    logo?: MediaObject;
    identifiableName?: string;
}
