/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Code } from './code';
import { ContactPoint } from './contactPoint';
import { EntitlementDTO } from './entitlementDTO';
import { Identifier } from './identifier';
import { LearningAchievementDTO } from './learningAchievementDTO';
import { LearningActivityDTO } from './learningActivityDTO';
import { LegalIdentifier } from './legalIdentifier';
import { LocationDTO } from './locationDTO';
import { Note } from './note';
import { Text } from './text';


export interface PersonDTO { 
<<<<<<< HEAD
    id?: string;
    identifier?: Array<Identifier>;
    type?: Array<Code>;
    preferredName?: Text;
    alternativeName?: Array<Text>;
    note?: Array<Note>;
    hasLocation?: Array<LocationDTO>;
    contactPoint?: Array<ContactPoint>;
    nationalId?: LegalIdentifier;
    fullName?: Text;
    givenNames?: Text;
    familyName?: Text;
    dateOfBirth?: Date;
=======
    id: string;
    identifier?: Array<Identifier>;
    type?: Array<Code>;
    note?: Array<Note>;
    contactPoint?: Array<ContactPoint>;
    preferredName?: Text;
    alternativeName?: Array<Text>;
    hasLocation?: Array<LocationDTO>;
    nationalId?: LegalIdentifier;
    fullName?: Text;
    givenNames: Text;
    familyName: Text;
    dateOfBirth: Date;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
    placeOfBirth?: LocationDTO;
    gender?: Code;
    citizenshipCountry?: Array<Code>;
    performed?: Array<LearningActivityDTO>;
    achieved?: Array<LearningAchievementDTO>;
    entitledTo?: Array<EntitlementDTO>;
    identifiableName?: string;
}
