/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Amount } from './amount';
import { Identifier } from './identifier';
import { Note } from './note';
import { Text } from './text';


export interface PriceDetailsDTO { 
    id?: string;
    identifier?: Array<Identifier>;
    amount?: Amount;
    name?: Text;
    description?: Note;
    additionalNote?: Array<Note>;
    identifiableName?: string;
}
