/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DetailedReport } from './detailedReport';
import { DiagnosticData } from './diagnosticData';
import { SimpleReport } from './simpleReport';


export interface Reports { 
    diagnosticData?: DiagnosticData;
    detailedReport?: DetailedReport;
    xmlDiagnosticData?: string;
    xmlDetailedReport?: string;
    simpleReport?: SimpleReport;
    xmlSimpleReport?: string;
    simpleReportJaxb?: SimpleReport;
<<<<<<< HEAD
    detailedReportJaxb?: DetailedReport;
    diagnosticDataJaxb?: DiagnosticData;
=======
    diagnosticDataJaxb?: DiagnosticData;
    detailedReportJaxb?: DetailedReport;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
}
