/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { XmlSimpleReport } from './xmlSimpleReport';


export interface SimpleReport { 
<<<<<<< HEAD
    jaxbModel?: XmlSimpleReport;
    validSignaturesCount?: number;
    validationTime?: Date;
    signatureIdList?: Array<string>;
    signaturesCount?: number;
    firstSignatureId?: string;
=======
    signaturesCount?: number;
    validSignaturesCount?: number;
    validationTime?: Date;
    firstSignatureId?: string;
    signatureIdList?: Array<string>;
    jaxbModel?: XmlSimpleReport;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
}
