/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Identifier } from './identifier';
import { Note } from './note';
import { Text } from './text';
import { WebDocumentDTO } from './webDocumentDTO';


export interface Standard { 
    id?: string;
    identifier?: Array<Identifier>;
    title?: Text;
    description?: Note;
    supplementaryDocument?: Array<WebDocumentDTO>;
<<<<<<< HEAD
=======
    identifiableName?: string;
>>>>>>> 98214b45d868ddd254c561669c1269836e81bd88
}
