/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TrustedServiceWrapper { 
    tspName?: string;
    serviceName?: string;
    countryCode?: string;
    status?: string;
    type?: string;
    startDate?: Date;
    endDate?: Date;
    capturedQualifiers?: Array<string>;
    additionalServiceInfos?: Array<string>;
}
