/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { XmlCV } from './xmlCV';
import { XmlCertificateChain } from './xmlCertificateChain';
import { XmlConclusion } from './xmlConclusion';
import { XmlFC } from './xmlFC';
import { XmlISC } from './xmlISC';
import { XmlPCV } from './xmlPCV';
import { XmlPSV } from './xmlPSV';
import { XmlSAV } from './xmlSAV';
import { XmlVCI } from './xmlVCI';
import { XmlVTS } from './xmlVTS';
import { XmlXCV } from './xmlXCV';


export interface XmlBasicBuildingBlocks { 
    fc?: XmlFC;
    isc?: XmlISC;
    vci?: XmlVCI;
    cv?: XmlCV;
    sav?: XmlSAV;
    xcv?: XmlXCV;
    psv?: XmlPSV;
    pcv?: XmlPCV;
    vts?: XmlVTS;
    certificateChain: XmlCertificateChain;
    conclusion: XmlConclusion;
    id?: string;
    type?: XmlBasicBuildingBlocks.TypeEnum;
}
export namespace XmlBasicBuildingBlocks {
    export type TypeEnum = 'SIGNATURE' | 'COUNTER_SIGNATURE' | 'TIMESTAMP' | 'REVOCATION' | 'CERTIFICATE';
    export const TypeEnum = {
        SIGNATURE: 'SIGNATURE' as TypeEnum,
        COUNTERSIGNATURE: 'COUNTER_SIGNATURE' as TypeEnum,
        TIMESTAMP: 'TIMESTAMP' as TypeEnum,
        REVOCATION: 'REVOCATION' as TypeEnum,
        CERTIFICATE: 'CERTIFICATE' as TypeEnum
    };
}
