/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { XmlName } from './xmlName';


export interface XmlConclusion { 
    indication: XmlConclusion.IndicationEnum;
    subIndication?: XmlConclusion.SubIndicationEnum;
    errors?: Array<XmlName>;
    warnings?: Array<XmlName>;
    infos?: Array<XmlName>;
}
export namespace XmlConclusion {
    export type IndicationEnum = 'TOTAL_PASSED' | 'PASSED' | 'INDETERMINATE' | 'FAILED' | 'TOTAL_FAILED';
    export const IndicationEnum = {
        TOTALPASSED: 'TOTAL_PASSED' as IndicationEnum,
        PASSED: 'PASSED' as IndicationEnum,
        INDETERMINATE: 'INDETERMINATE' as IndicationEnum,
        FAILED: 'FAILED' as IndicationEnum,
        TOTALFAILED: 'TOTAL_FAILED' as IndicationEnum
    };
    export type SubIndicationEnum = 'NO_SIGNING_CERTIFICATE_FOUND' | 'FORMAT_FAILURE' | 'POLICY_PROCESSING_ERROR' | 'SIGNATURE_POLICY_NOT_AVAILABLE' | 'OUT_OF_BOUNDS_NO_POE' | 'NO_CERTIFICATE_CHAIN_FOUND' | 'TRY_LATER' | 'REVOKED_NO_POE' | 'REVOKED_CA_NO_POE' | 'CHAIN_CONSTRAINTS_FAILURE' | 'CRYPTO_CONSTRAINTS_FAILURE' | 'CRYPTO_CONSTRAINTS_FAILURE_NO_POE' | 'SIGNED_DATA_NOT_FOUND' | 'HASH_FAILURE' | 'SIG_CRYPTO_FAILURE' | 'SIG_CONSTRAINTS_FAILURE' | 'NOT_YET_VALID' | 'TIMESTAMP_ORDER_FAILURE' | 'REVOKED' | 'EXPIRED' | 'NO_POE' | 'CERTIFICATE_CHAIN_GENERAL_FAILURE' | 'UNEXPECTED_ERROR';
    export const SubIndicationEnum = {
        NOSIGNINGCERTIFICATEFOUND: 'NO_SIGNING_CERTIFICATE_FOUND' as SubIndicationEnum,
        FORMATFAILURE: 'FORMAT_FAILURE' as SubIndicationEnum,
        POLICYPROCESSINGERROR: 'POLICY_PROCESSING_ERROR' as SubIndicationEnum,
        SIGNATUREPOLICYNOTAVAILABLE: 'SIGNATURE_POLICY_NOT_AVAILABLE' as SubIndicationEnum,
        OUTOFBOUNDSNOPOE: 'OUT_OF_BOUNDS_NO_POE' as SubIndicationEnum,
        NOCERTIFICATECHAINFOUND: 'NO_CERTIFICATE_CHAIN_FOUND' as SubIndicationEnum,
        TRYLATER: 'TRY_LATER' as SubIndicationEnum,
        REVOKEDNOPOE: 'REVOKED_NO_POE' as SubIndicationEnum,
        REVOKEDCANOPOE: 'REVOKED_CA_NO_POE' as SubIndicationEnum,
        CHAINCONSTRAINTSFAILURE: 'CHAIN_CONSTRAINTS_FAILURE' as SubIndicationEnum,
        CRYPTOCONSTRAINTSFAILURE: 'CRYPTO_CONSTRAINTS_FAILURE' as SubIndicationEnum,
        CRYPTOCONSTRAINTSFAILURENOPOE: 'CRYPTO_CONSTRAINTS_FAILURE_NO_POE' as SubIndicationEnum,
        SIGNEDDATANOTFOUND: 'SIGNED_DATA_NOT_FOUND' as SubIndicationEnum,
        HASHFAILURE: 'HASH_FAILURE' as SubIndicationEnum,
        SIGCRYPTOFAILURE: 'SIG_CRYPTO_FAILURE' as SubIndicationEnum,
        SIGCONSTRAINTSFAILURE: 'SIG_CONSTRAINTS_FAILURE' as SubIndicationEnum,
        NOTYETVALID: 'NOT_YET_VALID' as SubIndicationEnum,
        TIMESTAMPORDERFAILURE: 'TIMESTAMP_ORDER_FAILURE' as SubIndicationEnum,
        REVOKED: 'REVOKED' as SubIndicationEnum,
        EXPIRED: 'EXPIRED' as SubIndicationEnum,
        NOPOE: 'NO_POE' as SubIndicationEnum,
        CERTIFICATECHAINGENERALFAILURE: 'CERTIFICATE_CHAIN_GENERAL_FAILURE' as SubIndicationEnum,
        UNEXPECTEDERROR: 'UNEXPECTED_ERROR' as SubIndicationEnum
    };
}
