/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { XmlManifestFile } from './xmlManifestFile';


export interface XmlContainerInfo { 
    containerType?: string;
    zipComment?: string;
    mimeTypeFilePresent?: boolean;
    mimeTypeContent?: string;
    manifestFiles?: Array<XmlManifestFile>;
    contentFiles?: Array<string>;
}
