/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { XmlName } from './xmlName';


export interface XmlConstraint { 
    name: XmlName;
    status: XmlConstraint.StatusEnum;
    error?: XmlName;
    warning?: XmlName;
    info?: XmlName;
    additionalInfo?: string;
    id?: string;
}
export namespace XmlConstraint {
    export type StatusEnum = 'OK' | 'NOT_OK' | 'IGNORED' | 'INFORMATION' | 'WARNING';
    export const StatusEnum = {
        OK: 'OK' as StatusEnum,
        NOTOK: 'NOT_OK' as StatusEnum,
        IGNORED: 'IGNORED' as StatusEnum,
        INFORMATION: 'INFORMATION' as StatusEnum,
        WARNING: 'WARNING' as StatusEnum
    };
}
