/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface XmlDigestMatcher { 
    digestMethod?: string;
    digestValue?: string;
    dataFound?: boolean;
    dataIntact?: boolean;
    type?: XmlDigestMatcher.TypeEnum;
    name?: string;
}
export namespace XmlDigestMatcher {
    export type TypeEnum = 'REFERENCE' | 'OBJECT' | 'MANIFEST' | 'MANIFEST_ENTRY' | 'SIGNED_PROPERTIES' | 'MESSAGE_DIGEST' | 'MESSAGE_IMPRINT';
    export const TypeEnum = {
        REFERENCE: 'REFERENCE' as TypeEnum,
        OBJECT: 'OBJECT' as TypeEnum,
        MANIFEST: 'MANIFEST' as TypeEnum,
        MANIFESTENTRY: 'MANIFEST_ENTRY' as TypeEnum,
        SIGNEDPROPERTIES: 'SIGNED_PROPERTIES' as TypeEnum,
        MESSAGEDIGEST: 'MESSAGE_DIGEST' as TypeEnum,
        MESSAGEIMPRINT: 'MESSAGE_IMPRINT' as TypeEnum
    };
}
