/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { XmlPolicy } from './xmlPolicy';
import { XmlSignature } from './xmlSignature';


export interface XmlSimpleReport { 
    policy: XmlPolicy;
    validationTime: Date;
    documentName: string;
    validSignaturesCount?: number;
    signaturesCount?: number;
    containerType?: string;
    signature?: Array<XmlSignature>;
}
