/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { XmlCertificateChain } from './xmlCertificateChain';
import { XmlSignatureLevel } from './xmlSignatureLevel';
import { XmlSignatureScope } from './xmlSignatureScope';


export interface XmlSignature { 
    filename?: string;
    signingTime?: Date;
    bestSignatureTime?: Date;
    signedBy?: string;
    certificateChain?: XmlCertificateChain;
    signatureLevel?: XmlSignatureLevel;
    indication: XmlSignature.IndicationEnum;
    subIndication?: XmlSignature.SubIndicationEnum;
    errors?: Array<string>;
    warnings?: Array<string>;
    infos?: Array<string>;
    signatureScope?: Array<XmlSignatureScope>;
    id?: string;
    counterSignature?: boolean;
    parentId?: string;
    signatureFormat?: XmlSignature.SignatureFormatEnum;
}
export namespace XmlSignature {
    export type IndicationEnum = 'TOTAL_PASSED' | 'TOTAL_FAILED' | 'INDETERMINATE' | 'PASSED' | 'FAILED' | 'NO_SIGNATURE_FOUND';
    export const IndicationEnum = {
        TOTALPASSED: 'TOTAL_PASSED' as IndicationEnum,
        TOTALFAILED: 'TOTAL_FAILED' as IndicationEnum,
        INDETERMINATE: 'INDETERMINATE' as IndicationEnum,
        PASSED: 'PASSED' as IndicationEnum,
        FAILED: 'FAILED' as IndicationEnum,
        NOSIGNATUREFOUND: 'NO_SIGNATURE_FOUND' as IndicationEnum
    };
    export type SubIndicationEnum = 'FORMAT_FAILURE' | 'HASH_FAILURE' | 'SIG_CRYPTO_FAILURE' | 'REVOKED' | 'SIG_CONSTRAINTS_FAILURE' | 'CHAIN_CONSTRAINTS_FAILURE' | 'CERTIFICATE_CHAIN_GENERAL_FAILURE' | 'CRYPTO_CONSTRAINTS_FAILURE' | 'EXPIRED' | 'NOT_YET_VALID' | 'POLICY_PROCESSING_ERROR' | 'SIGNATURE_POLICY_NOT_AVAILABLE' | 'TIMESTAMP_ORDER_FAILURE' | 'NO_SIGNING_CERTIFICATE_FOUND' | 'NO_CERTIFICATE_CHAIN_FOUND' | 'REVOKED_NO_POE' | 'REVOKED_CA_NO_POE' | 'OUT_OF_BOUNDS_NO_POE' | 'CRYPTO_CONSTRAINTS_FAILURE_NO_POE' | 'NO_POE' | 'TRY_LATER' | 'SIGNED_DATA_NOT_FOUND';
    export const SubIndicationEnum = {
        FORMATFAILURE: 'FORMAT_FAILURE' as SubIndicationEnum,
        HASHFAILURE: 'HASH_FAILURE' as SubIndicationEnum,
        SIGCRYPTOFAILURE: 'SIG_CRYPTO_FAILURE' as SubIndicationEnum,
        REVOKED: 'REVOKED' as SubIndicationEnum,
        SIGCONSTRAINTSFAILURE: 'SIG_CONSTRAINTS_FAILURE' as SubIndicationEnum,
        CHAINCONSTRAINTSFAILURE: 'CHAIN_CONSTRAINTS_FAILURE' as SubIndicationEnum,
        CERTIFICATECHAINGENERALFAILURE: 'CERTIFICATE_CHAIN_GENERAL_FAILURE' as SubIndicationEnum,
        CRYPTOCONSTRAINTSFAILURE: 'CRYPTO_CONSTRAINTS_FAILURE' as SubIndicationEnum,
        EXPIRED: 'EXPIRED' as SubIndicationEnum,
        NOTYETVALID: 'NOT_YET_VALID' as SubIndicationEnum,
        POLICYPROCESSINGERROR: 'POLICY_PROCESSING_ERROR' as SubIndicationEnum,
        SIGNATUREPOLICYNOTAVAILABLE: 'SIGNATURE_POLICY_NOT_AVAILABLE' as SubIndicationEnum,
        TIMESTAMPORDERFAILURE: 'TIMESTAMP_ORDER_FAILURE' as SubIndicationEnum,
        NOSIGNINGCERTIFICATEFOUND: 'NO_SIGNING_CERTIFICATE_FOUND' as SubIndicationEnum,
        NOCERTIFICATECHAINFOUND: 'NO_CERTIFICATE_CHAIN_FOUND' as SubIndicationEnum,
        REVOKEDNOPOE: 'REVOKED_NO_POE' as SubIndicationEnum,
        REVOKEDCANOPOE: 'REVOKED_CA_NO_POE' as SubIndicationEnum,
        OUTOFBOUNDSNOPOE: 'OUT_OF_BOUNDS_NO_POE' as SubIndicationEnum,
        CRYPTOCONSTRAINTSFAILURENOPOE: 'CRYPTO_CONSTRAINTS_FAILURE_NO_POE' as SubIndicationEnum,
        NOPOE: 'NO_POE' as SubIndicationEnum,
        TRYLATER: 'TRY_LATER' as SubIndicationEnum,
        SIGNEDDATANOTFOUND: 'SIGNED_DATA_NOT_FOUND' as SubIndicationEnum
    };
    export type SignatureFormatEnum = 'XML_NOT_ETSI' | 'XAdES_C' | 'XAdES_X' | 'XAdES_XL' | 'XAdES_A' | 'XAdES_BASELINE_LTA' | 'XAdES_BASELINE_LT' | 'XAdES_BASELINE_T' | 'XAdES_BASELINE_B' | 'CMS_NOT_ETSI' | 'CAdES_BASELINE_LTA' | 'CAdES_BASELINE_LT' | 'CAdES_BASELINE_T' | 'CAdES_BASELINE_B' | 'CAdES_101733_C' | 'CAdES_101733_X' | 'CAdES_101733_A' | 'PDF_NOT_ETSI' | 'PAdES_BASELINE_LTA' | 'PAdES_BASELINE_LT' | 'PAdES_BASELINE_T' | 'PAdES_BASELINE_B' | 'PKCS7_B' | 'PKCS7_T' | 'PKCS7_LT' | 'PKCS7_LTA' | 'UNKNOWN';
    export const SignatureFormatEnum = {
        XMLNOTETSI: 'XML_NOT_ETSI' as SignatureFormatEnum,
        XAdESC: 'XAdES_C' as SignatureFormatEnum,
        XAdESX: 'XAdES_X' as SignatureFormatEnum,
        XAdESXL: 'XAdES_XL' as SignatureFormatEnum,
        XAdESA: 'XAdES_A' as SignatureFormatEnum,
        XAdESBASELINELTA: 'XAdES_BASELINE_LTA' as SignatureFormatEnum,
        XAdESBASELINELT: 'XAdES_BASELINE_LT' as SignatureFormatEnum,
        XAdESBASELINET: 'XAdES_BASELINE_T' as SignatureFormatEnum,
        XAdESBASELINEB: 'XAdES_BASELINE_B' as SignatureFormatEnum,
        CMSNOTETSI: 'CMS_NOT_ETSI' as SignatureFormatEnum,
        CAdESBASELINELTA: 'CAdES_BASELINE_LTA' as SignatureFormatEnum,
        CAdESBASELINELT: 'CAdES_BASELINE_LT' as SignatureFormatEnum,
        CAdESBASELINET: 'CAdES_BASELINE_T' as SignatureFormatEnum,
        CAdESBASELINEB: 'CAdES_BASELINE_B' as SignatureFormatEnum,
        CAdES101733C: 'CAdES_101733_C' as SignatureFormatEnum,
        CAdES101733X: 'CAdES_101733_X' as SignatureFormatEnum,
        CAdES101733A: 'CAdES_101733_A' as SignatureFormatEnum,
        PDFNOTETSI: 'PDF_NOT_ETSI' as SignatureFormatEnum,
        PAdESBASELINELTA: 'PAdES_BASELINE_LTA' as SignatureFormatEnum,
        PAdESBASELINELT: 'PAdES_BASELINE_LT' as SignatureFormatEnum,
        PAdESBASELINET: 'PAdES_BASELINE_T' as SignatureFormatEnum,
        PAdESBASELINEB: 'PAdES_BASELINE_B' as SignatureFormatEnum,
        PKCS7B: 'PKCS7_B' as SignatureFormatEnum,
        PKCS7T: 'PKCS7_T' as SignatureFormatEnum,
        PKCS7LT: 'PKCS7_LT' as SignatureFormatEnum,
        PKCS7LTA: 'PKCS7_LTA' as SignatureFormatEnum,
        UNKNOWN: 'UNKNOWN' as SignatureFormatEnum
    };
}
