/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface XmlSignatureLevel { 
    value?: XmlSignatureLevel.ValueEnum;
    description?: string;
}
export namespace XmlSignatureLevel {
    export type ValueEnum = 'QESIG' | 'QESEAL' | 'QES' | 'ADESIG_QC' | 'ADESEAL_QC' | 'ADES_QC' | 'ADESIG' | 'ADESEAL' | 'ADES' | 'INDETERMINATE_QESIG' | 'INDETERMINATE_QESEAL' | 'INDETERMINATE_QES' | 'INDETERMINATE_ADESIG_QC' | 'INDETERMINATE_ADESEAL_QC' | 'INDETERMINATE_ADES_QC' | 'INDETERMINATE_ADESIG' | 'INDETERMINATE_ADESEAL' | 'INDETERMINATE_ADES' | 'NOT_ADES_QC_QSCD' | 'NOT_ADES_QC' | 'NOT_ADES' | 'NA';
    export const ValueEnum = {
        QESIG: 'QESIG' as ValueEnum,
        QESEAL: 'QESEAL' as ValueEnum,
        QES: 'QES' as ValueEnum,
        ADESIGQC: 'ADESIG_QC' as ValueEnum,
        ADESEALQC: 'ADESEAL_QC' as ValueEnum,
        ADESQC: 'ADES_QC' as ValueEnum,
        ADESIG: 'ADESIG' as ValueEnum,
        ADESEAL: 'ADESEAL' as ValueEnum,
        ADES: 'ADES' as ValueEnum,
        INDETERMINATEQESIG: 'INDETERMINATE_QESIG' as ValueEnum,
        INDETERMINATEQESEAL: 'INDETERMINATE_QESEAL' as ValueEnum,
        INDETERMINATEQES: 'INDETERMINATE_QES' as ValueEnum,
        INDETERMINATEADESIGQC: 'INDETERMINATE_ADESIG_QC' as ValueEnum,
        INDETERMINATEADESEALQC: 'INDETERMINATE_ADESEAL_QC' as ValueEnum,
        INDETERMINATEADESQC: 'INDETERMINATE_ADES_QC' as ValueEnum,
        INDETERMINATEADESIG: 'INDETERMINATE_ADESIG' as ValueEnum,
        INDETERMINATEADESEAL: 'INDETERMINATE_ADESEAL' as ValueEnum,
        INDETERMINATEADES: 'INDETERMINATE_ADES' as ValueEnum,
        NOTADESQCQSCD: 'NOT_ADES_QC_QSCD' as ValueEnum,
        NOTADESQC: 'NOT_ADES_QC' as ValueEnum,
        NOTADES: 'NOT_ADES' as ValueEnum,
        NA: 'NA' as ValueEnum
    };
}
