/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { XmlBasicSignature } from './xmlBasicSignature';
import { XmlChainItem } from './xmlChainItem';
import { XmlDigestMatcher } from './xmlDigestMatcher';
import { XmlSigningCertificate } from './xmlSigningCertificate';
import { XmlTimestampedObject } from './xmlTimestampedObject';


export interface XmlTimestamp { 
    productionTime: Date;
    digestMatcher: XmlDigestMatcher;
    basicSignature: XmlBasicSignature;
    signingCertificate?: XmlSigningCertificate;
    certificateChain?: Array<XmlChainItem>;
    timestampedObjects?: Array<XmlTimestampedObject>;
    base64Encoded?: Array<string>;
    id?: string;
    type?: string;
}
