/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { XmlDigestAlgoAndValue } from './xmlDigestAlgoAndValue';


export interface XmlTimestampedObject { 
    digestAlgoAndValue?: XmlDigestAlgoAndValue;
    id?: string;
    category?: XmlTimestampedObject.CategoryEnum;
}
export namespace XmlTimestampedObject {
    export type CategoryEnum = 'SIGNATURE' | 'CERTIFICATE' | 'REVOCATION' | 'TIMESTAMP';
    export const CategoryEnum = {
        SIGNATURE: 'SIGNATURE' as CategoryEnum,
        CERTIFICATE: 'CERTIFICATE' as CategoryEnum,
        REVOCATION: 'REVOCATION' as CategoryEnum,
        TIMESTAMP: 'TIMESTAMP' as CategoryEnum
    };
}
