/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface XmlTrustedService { 
    serviceName: string;
    serviceType: string;
    status: string;
    startDate: Date;
    endDate?: Date;
    capturedQualifiers?: Array<string>;
    additionalServiceInfoUris?: Array<string>;
    serviceSupplyPoints?: Array<string>;
    expiredCertsRevocationInfo?: Date;
}
