/**
 * Wallet API
 * API Wallet description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: edci.support@eu.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { XmlConclusion } from './xmlConclusion';
import { XmlConstraint } from './xmlConstraint';
import { XmlValidationCertificateQualification } from './xmlValidationCertificateQualification';


export interface XmlValidationSignatureQualification { 
    constraint?: Array<XmlConstraint>;
    conclusion: XmlConclusion;
    validationCertificateQualification?: Array<XmlValidationCertificateQualification>;
    id?: string;
    signatureQualification?: XmlValidationSignatureQualification.SignatureQualificationEnum;
}
export namespace XmlValidationSignatureQualification {
    export type SignatureQualificationEnum = 'QESIG' | 'QESEAL' | 'QES' | 'ADESIG_QC' | 'ADESEAL_QC' | 'ADES_QC' | 'ADESIG' | 'ADESEAL' | 'ADES' | 'INDETERMINATE_QESIG' | 'INDETERMINATE_QESEAL' | 'INDETERMINATE_QES' | 'INDETERMINATE_ADESIG_QC' | 'INDETERMINATE_ADESEAL_QC' | 'INDETERMINATE_ADES_QC' | 'INDETERMINATE_ADESIG' | 'INDETERMINATE_ADESEAL' | 'INDETERMINATE_ADES' | 'NOT_ADES_QC_QSCD' | 'NOT_ADES_QC' | 'NOT_ADES' | 'NA';
    export const SignatureQualificationEnum = {
        QESIG: 'QESIG' as SignatureQualificationEnum,
        QESEAL: 'QESEAL' as SignatureQualificationEnum,
        QES: 'QES' as SignatureQualificationEnum,
        ADESIGQC: 'ADESIG_QC' as SignatureQualificationEnum,
        ADESEALQC: 'ADESEAL_QC' as SignatureQualificationEnum,
        ADESQC: 'ADES_QC' as SignatureQualificationEnum,
        ADESIG: 'ADESIG' as SignatureQualificationEnum,
        ADESEAL: 'ADESEAL' as SignatureQualificationEnum,
        ADES: 'ADES' as SignatureQualificationEnum,
        INDETERMINATEQESIG: 'INDETERMINATE_QESIG' as SignatureQualificationEnum,
        INDETERMINATEQESEAL: 'INDETERMINATE_QESEAL' as SignatureQualificationEnum,
        INDETERMINATEQES: 'INDETERMINATE_QES' as SignatureQualificationEnum,
        INDETERMINATEADESIGQC: 'INDETERMINATE_ADESIG_QC' as SignatureQualificationEnum,
        INDETERMINATEADESEALQC: 'INDETERMINATE_ADESEAL_QC' as SignatureQualificationEnum,
        INDETERMINATEADESQC: 'INDETERMINATE_ADES_QC' as SignatureQualificationEnum,
        INDETERMINATEADESIG: 'INDETERMINATE_ADESIG' as SignatureQualificationEnum,
        INDETERMINATEADESEAL: 'INDETERMINATE_ADESEAL' as SignatureQualificationEnum,
        INDETERMINATEADES: 'INDETERMINATE_ADES' as SignatureQualificationEnum,
        NOTADESQCQSCD: 'NOT_ADES_QC_QSCD' as SignatureQualificationEnum,
        NOTADESQC: 'NOT_ADES_QC' as SignatureQualificationEnum,
        NOTADES: 'NOT_ADES' as SignatureQualificationEnum,
        NA: 'NA' as SignatureQualificationEnum
    };
}
