/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IdentifierFieldView } from './identifierFieldView';
import { LinkFieldView } from './linkFieldView';
import { NoteFieldView } from './noteFieldView';
import { OrganizationTabView } from './organizationTabView';
import { QualificationFieldView } from './qualificationFieldView';


export interface AccreditationFieldView { 
    id?: string;
    identifier?: Array<IdentifierFieldView>;
    dcType?: LinkFieldView;
    title?: string;
    description?: string;
    decision?: string;
    status?: string;
    report?: LinkFieldView;
    organisation?: OrganizationTabView;
    limitQualification?: QualificationFieldView;
    limitField?: Array<string>;
    limitEQFLevel?: Array<string>;
    limitCredentialType?: Array<string>;
    limitJurisdiction?: Array<string>;
    accreditingAgent?: OrganizationTabView;
    dateIssued?: string;
    reviewDate?: string;
    expiryDate?: string;
    dateModified?: string;
    valid?: string;
    additionalNote?: Array<NoteFieldView>;
    homePage?: Array<LinkFieldView>;
    supplementaryDocument?: Array<LinkFieldView>;
    landingPage?: Array<LinkFieldView>;
}
