/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AchievementSpecTabView } from './achievementSpecTabView';
import { ActivityTabView } from './activityTabView';
import { AssessmentTabView } from './assessmentTabView';
import { EntitlementTabView } from './entitlementTabView';
import { IdentifierFieldView } from './identifierFieldView';
import { NoteFieldView } from './noteFieldView';
import { OrganizationTabView } from './organizationTabView';


export interface AchievementTabView { 
    id?: string;
    title?: string;
    identifier?: Array<IdentifierFieldView>;
    awardingDate?: string;
    awardingBody?: OrganizationTabView;
    description?: string;
    provenBy?: Array<AssessmentTabView>;
    influencedBy?: Array<ActivityTabView>;
    entitledOwnerTo?: Array<EntitlementTabView>;
    subAchievements?: Array<AchievementTabView>;
    moreInformation?: Array<NoteFieldView>;
    specifiedBy?: AchievementSpecTabView;
}
