/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IdentifierFieldView } from './identifierFieldView';
import { LearningOutcomeFieldView } from './learningOutcomeFieldView';
import { LinkFieldView } from './linkFieldView';
import { NoteFieldView } from './noteFieldView';
import { QualificationFieldView } from './qualificationFieldView';


export interface AchievementSpecTabView { 
    homePage?: Array<LinkFieldView>;
    identifier?: Array<IdentifierFieldView>;
    learningOutcome?: Array<LearningOutcomeFieldView>;
    definition?: string;
    workloadInHours?: string;
    maximumDurationInMonths?: string;
    ectsCreditPoints?: string;
    creditPoints?: Array<string>;
    thematicArea?: Array<string>;
    learningMode?: Array<string>;
    instructionLanguage?: Array<string>;
    learningSetting?: string;
    learningOpportunityType?: Array<string>;
    entryRequirements?: string;
    otherDocuments?: Array<LinkFieldView>;
    moreInformation?: Array<NoteFieldView>;
    qualification?: QualificationFieldView;
}
