/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AchievementTabView } from './achievementTabView';
import { ActivitySpecTabView } from './activitySpecTabView';
import { AgentView } from './agentView';
import { AwardingProcessFieldView } from './awardingProcessFieldView';
import { IdentifierFieldView } from './identifierFieldView';
import { LearningOpportunityFieldView } from './learningOpportunityFieldView';
import { LinkFieldView } from './linkFieldView';
import { LocationFieldView } from './locationFieldView';
import { NoteFieldView } from './noteFieldView';
import { PeriodOfTimeFieldView } from './periodOfTimeFieldView';


export interface ActivityTabView { 
    awardedBy?: AwardingProcessFieldView;
    description?: Array<string>;
    identifier?: Array<IdentifierFieldView>;
    additionalNote?: Array<NoteFieldView>;
    supplementaryDocument?: Array<LinkFieldView>;
    title?: string;
    dcType?: Array<string>;
    id?: string;
    temporal?: Array<PeriodOfTimeFieldView>;
    workload?: string;
    directedBy?: Array<AgentView>;
    levelOfCompletion?: number;
    locations?: Array<LocationFieldView>;
    influences?: Array<AchievementTabView>;
    isPartOf?: Array<ActivityTabView>;
    subActivities?: Array<ActivityTabView>;
    specifiedBy?: ActivitySpecTabView;
    learningOpportunity?: LearningOpportunityFieldView;
}
