/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AchievementTabView } from './achievementTabView';
import { ActivitySpecTabView } from './activitySpecTabView';
import { IdentifierFieldView } from './identifierFieldView';
import { LocationFieldView } from './locationFieldView';
import { NoteFieldView } from './noteFieldView';
import { OrganizationTabView } from './organizationTabView';


export interface ActivityTabView { 
    id?: string;
    title?: string;
    identifier?: Array<IdentifierFieldView>;
    description?: string;
    startDate?: string;
    endDate?: string;
    workloadInHours?: string;
    directedBy?: OrganizationTabView;
    location?: Array<LocationFieldView>;
    influenced?: Array<AchievementTabView>;
    subActivities?: Array<ActivityTabView>;
    moreInformation?: Array<NoteFieldView>;
    specifiedBy?: ActivitySpecTabView;
}
