/**
 * Viewer's API
 * Viewer's public API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: EMPL-ELM-SUPPORT@ec.europa.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AchievementTabView } from './achievementTabView';
import { AgentView } from './agentView';
import { AssessmentSpecTabView } from './assessmentSpecTabView';
import { AwardingProcessFieldView } from './awardingProcessFieldView';
import { IdentifierFieldView } from './identifierFieldView';
import { LinkFieldView } from './linkFieldView';
import { LocationFieldView } from './locationFieldView';
import { NoteFieldView } from './noteFieldView';
import { ResultDistributionFieldView } from './resultDistributionFieldView';
import { ShortenedGradingFieldView } from './shortenedGradingFieldView';


export interface AssessmentTabView { 
    awardedBy?: AwardingProcessFieldView;
    description?: Array<string>;
    identifier?: Array<IdentifierFieldView>;
    additionalNote?: Array<NoteFieldView>;
    supplementaryDocument?: Array<LinkFieldView>;
    title?: string;
    dcType?: Array<string>;
    id?: string;
    grade?: NoteFieldView;
    gradeStatus?: string;
    location?: LocationFieldView;
    proves?: AchievementTabView;
    resultDistribution?: ResultDistributionFieldView;
    shortenedGrading?: ShortenedGradingFieldView;
    assessedBy?: Array<AgentView>;
    idVerification?: string;
    dateIssued?: string;
    subAssessments?: Array<AssessmentTabView>;
    isPartOf?: Array<AssessmentTabView>;
    specifiedBy?: AssessmentSpecTabView;
}
