/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssessmentSpecTabView } from './assessmentSpecTabView';
import { IdentifierFieldView } from './identifierFieldView';
import { NoteFieldView } from './noteFieldView';
import { OrganizationTabView } from './organizationTabView';


export interface AssessmentTabView { 
    id?: string;
    title?: string;
    grade?: string;
    identifier?: Array<IdentifierFieldView>;
    conductedBy?: OrganizationTabView;
    idVerification?: string;
    description?: string;
    issuedDate?: string;
    subAssessments?: Array<AssessmentTabView>;
    moreInformation?: Array<NoteFieldView>;
    specifiedBy?: AssessmentSpecTabView;
}
