/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IdentifierFieldView } from './identifierFieldView';
import { LinkFieldView } from './linkFieldView';
import { NoteFieldView } from './noteFieldView';
import { ResultDistributionFieldView } from './resultDistributionFieldView';
import { ScoringSchemeFieldView } from './scoringSchemeFieldView';
import { ShortenedGradingFieldView } from './shortenedGradingFieldView';


export interface AssessmentSpecTabView { 
    homePage?: Array<LinkFieldView>;
    title?: string;
    identifier?: Array<IdentifierFieldView>;
    description?: string;
    type?: Array<string>;
    mode?: string;
    language?: Array<string>;
    supplementaryDocument?: Array<LinkFieldView>;
    moreInformation?: Array<NoteFieldView>;
    gradingScheme?: ScoringSchemeFieldView;
    resultDistribution?: ResultDistributionFieldView;
    shortenedGrading?: ShortenedGradingFieldView;
}
