/**
 * Viewer's API
 * Viewer's public API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: EMPL-ELM-SUPPORT@ec.europa.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InputStream } from './inputStream';


export interface ByteArrayResource { 
    byteArray?: Array<string>;
    description?: string;
    inputStream?: InputStream;
    open?: boolean;
    file?: Blob;
    url?: string;
    readable?: boolean;
    uri?: string;
    filename?: string;
}
