/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConceptSchemeDTO } from './conceptSchemeDTO';


export interface ConceptDTO { 
    id: string;
    type?: string;
    inScheme?: ConceptSchemeDTO;
    prefLabel?: { [key: string]: Array<string>; };
    notation?: string;
    name?: string;
}
