/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressFieldView } from './addressFieldView';
import { LinkFieldView } from './linkFieldView';
import { MailboxFieldView } from './mailboxFieldView';
import { PhoneFieldView } from './phoneFieldView';


export interface ContactPointFieldView { 
    address?: Array<AddressFieldView>;
    phone?: Array<PhoneFieldView>;
    emailAddress?: Array<MailboxFieldView>;
    contactForm?: Array<LinkFieldView>;
}
