/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CredentialMetadataTabView { 
    uuid?: string;
    title?: string;
    issuanceDate?: string;
    expirationDate?: string;
    description?: string;
    type?: string;
    vpType?: string;
    formatType?: string;
    xml?: string;
    primaryLanguage?: string;
    availableLanguages?: Array<string>;
}
