/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContactPointFieldView } from './contactPointFieldView';
import { IdentifierFieldView } from './identifierFieldView';
import { LocationFieldView } from './locationFieldView';


export interface CredentialSubjectTabView { 
    id?: string;
    givenNames?: string;
    fullName?: string;
    familyName?: string;
    dateOfBirth?: string;
    citizenshipCountry?: Array<string>;
    placeOfBirth?: LocationFieldView;
    nationalId?: string;
    contactPoint?: Array<ContactPointFieldView>;
    gender?: string;
    additionalNote?: Array<string>;
    identifier?: Array<IdentifierFieldView>;
    hasLocation?: Array<LocationFieldView>;
}
