/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IdentifierFieldView } from './identifierFieldView';
import { LinkFieldView } from './linkFieldView';
import { NoteFieldView } from './noteFieldView';
import { OrganizationTabView } from './organizationTabView';


export interface EntitlementSpecTabView { 
    homePage?: Array<LinkFieldView>;
    title?: string;
    identifier?: Array<IdentifierFieldView>;
    description?: string;
    entitlementType?: string;
    status?: string;
    validWith?: OrganizationTabView;
    validWithin?: Array<string>;
    toWorkAs?: Array<string>;
    otherDocs?: Array<LinkFieldView>;
    moreInformation?: Array<NoteFieldView>;
}
