/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EntitlementSpecTabView } from './entitlementSpecTabView';
import { IdentifierFieldView } from './identifierFieldView';
import { NoteFieldView } from './noteFieldView';


export interface EntitlementTabView { 
    id?: string;
    title?: string;
    identifier?: Array<IdentifierFieldView>;
    issuedDate?: string;
    expiryDate?: string;
    description?: string;
    subEntitlements?: Array<EntitlementTabView>;
    moreInformation?: Array<NoteFieldView>;
    specifiedBy?: EntitlementSpecTabView;
}
