/**
 * Viewer's API
 * Viewer's public API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: EMPL-ELM-SUPPORT@ec.europa.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CredentialMetadataTabView } from './credentialMetadataTabView';


export interface EuropassCredentialPresentationLiteView { 
    credentialMetadata?: CredentialMetadataTabView;
    subCredentials?: Array<EuropassCredentialPresentationLiteView>;
}
