/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IdentifierFieldView } from './identifierFieldView';
import { LinkFieldView } from './linkFieldView';


export interface GradingSchemeFieldView { 
    identifier?: Array<IdentifierFieldView>;
    title?: Array<string>;
    description?: Array<string>;
    supplementaryDocument?: Array<LinkFieldView>;
}
