/**
 * Viewer's API
 * Viewer's public API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: EMPL-ELM-SUPPORT@ec.europa.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConceptDTO } from './conceptDTO';


export interface Identifier { 
    id: string;
    type?: string;
    dateIssued?: Date;
    notation: string;
    creator?: string;
    schemeAgency?: { [key: string]: Array<string>; };
    schemeName?: string;
    schemeVersion?: string;
    schemeId?: string;
    dcType?: Array<ConceptDTO>;
    name?: string;
}
