/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConceptDTO } from './conceptDTO';


export interface Identifier { 
    id: string;
    type?: string;
    dateIssued?: Date;
    notation: string;
    creator?: string;
    schemeAgency?: { [key: string]: Array<string>; };
    schemeName?: string;
    schemeVersion?: string;
    dcType?: Array<ConceptDTO>;
    name?: string;
}
