/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface MediaObjectFieldView { 
    contentUrl?: string;
    content?: string;
    contentEncoding?: string;
    contentType?: string;
    contentSize?: number;
    attachmentType?: string;
    title?: string;
    description?: string;
}
