/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccreditationFieldView } from './accreditationFieldView';


export interface QualificationFieldView { 
    isPartialQualification?: boolean;
    qualificationCode?: Array<string>;
    accreditation?: Array<AccreditationFieldView>;
    nqflevel?: Array<string>;
    eqflevel?: string;
    partialQualification?: boolean;
}
