/**
 * API
 * API Swagger description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LinkFieldView } from './linkFieldView';


export interface VerificationCheckView { 
    id?: string;
    type?: LinkFieldView;
    status?: LinkFieldView;
    longDescription?: string;
    description?: string;
    longDescrAvailableLangs?: { [key: string]: string; };
    descrAvailableLangs?: { [key: string]: string; };
}
